USE lab_mysql;

CREATE TABLE Cars (ID int NOT NULL AUTO_INCREMENT, 
VIN VARCHAR(20), Manufacturer VARCHAR(20), Model VARCHAR(20), Year VARCHAR(4), Color VARCHAR(20),
PRIMARY KEY (ID)
);

CREATE TABLE Customers (ID int NOT NULL AUTO_INCREMENT, 
Customer_ID VARCHAR(20), Name VARCHAR(20), Mobile VARCHAR(20), Email VARCHAR(20), Address VARCHAR(60), 
City VARCHAR(20), State VARCHAR(20), Country VARCHAR(20),  ZIP VARCHAR(20),
PRIMARY KEY (ID)
);

CREATE TABLE Salespersons (ID int NOT NULL AUTO_INCREMENT, 
Staff_ID VARCHAR(20), Name VARCHAR(20), Store VARCHAR(20),
PRIMARY KEY (ID)
);

CREATE TABLE Invoices (ID int NOT NULL AUTO_INCREMENT, 
Invoice_number VARCHAR(20), Date DATE, Car VARCHAR(20), Customer VARCHAR(20), Salesperson VARCHAR(20),
PRIMARY KEY (ID)
);

SELECT * FROM Invoices;



